name: Build and Push to GHCR

on:
  push:
    branches: ["complete"]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./image
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/neovim:latest
            ghcr.io/${{ github.repository_owner }}/neovim:${{ steps.date.outputs.date }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
